---
fixtures:
  repositories:
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
    translate: 'git://github.com/puppetlabs/puppetlabs-translate.git'
  forge_modules:
    stdlib:
      repo: puppetlabs-stdlib
      ref: 5.2.0
    cron_core:
      repo: puppetlabs-cron_core
      ref: 1.0.1
    cron:
      repo: puppet-cron
      ref: 1.3.1
    scheduled_task:
      repo: puppetlabs-scheduled_task
      ref: 1.0.1
