all:
	cat ../lib/puppet_x/os_patching/os_patching.rb > clean_cache.rb
	cat ../tasks.real/clean_cache_real.rb >> clean_cache.rb
	chmod +x clean_cache.rb
	cat ../lib/puppet_x/os_patching/os_patching.rb > patch_server.rb
	cat ../tasks.real/patch_server_real.rb >> patch_server.rb
	chmod +x patch_server.rb